services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PGDATA: /data/postgres
    env_file:
      - .env
    volumes:
      - data:/data/postgres
    restart: always
    ports:
      - ${DATABASE_PORT}:5432

volumes:
  data: