import { ReactNode } from 'react'

import type { Metadata } from 'next'

import { Footer } from '@/components/layout/footer'
import { Header } from '@/components/layout/header'
import { Toaster } from '@/components/ui/toaster'
import { fontSans } from '@/lib/fonts'
import { initProfile } from '@/lib/init-profile'
import { cn } from '@/lib/utils'
import { Providers } from '@/providers'

import './globals.css'

export const metadata: Metadata = {
	title: 'The H8ter',
	description: 'Generated by create next app',
}

export default async function RootLayout({
	children,
}: {
	children: ReactNode
}) {
	await initProfile()

	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={cn(
					'min-h-screen bg-background font-sans antialiased',
					fontSans.variable,
				)}
			>
				<Providers>
					<Header />
					<main className="flex flex-col grow">{children}</main>
					<Footer />
					<Toaster />
					<div id="confetti-portal" />
				</Providers>
			</body>
		</html>
	)
}
